version: "3.2"
services: 
  cars-db:
    image: mysql:8
    ports:
      - "3309:3306"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.db
      - cars-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  cars-data:
    driver: local